
$scriptFileDirPath = if ($PSScriptRoot) { $PSScriptRoot } else { 'C:/Tools/PS/Windows' }

# 全局配置
$isWindowsHome = $true
$userName = 'zhangyf'
$ramDiskPath = 'Z:'
$ramDiskTempPath = "$ramDiskPath\Temp"
$isEnableAdministrator = $false
# Note: `$ramDiskPath` may be not available during init
$tempDirPath = 'Z:/'

$isManualEditHostFile = $false
$blockUrls = @('www.gilisoft.com',
               'gilisoft.com')

# set text edit tool
Set-Alias -Name edit -Value "C:\Program Files\Notepad++\notepad++.exe"

# set current location to avoid mistakes
Set-Location $tempDirPath

Set-ExecutionPolicy RemoteSigned -Force



# 配置Windows系统

# 系统设置

# 设置
# 关闭UAC
# 更新和安全：暂停更新，安全中心 关闭病毒和威胁防护和防火墙
# 系统：电源和睡眠 关闭睡眠，远程桌面 打开远程桌面
# 关闭：Windows声音

# 关闭休眠
powercfg -h off



# 设置并设置 Ramdiskz
# 安装 RAMDisk，设置盘符为 Z，大小 3072 MB
<# 启动时新建如下文件夹
Temp
Internet 临时文件
Cache\Edge\Cache
Cache\Edge\Code Cache
#>
# 将环境变量中的临时变量（Temp，Tmp），以及 IE 临时文件，Edge 缓存夹指向该盘

# Win+X-系统
# 高级：性能-最佳性能
# 系统保护：关闭系统还原
# 远程：关闭远程协助，允许远程桌面

# 磁盘分区 不允许索引内容

# 文件管理器 显示隐藏文件，打开时显示此电脑，隐私选项（不显示最近使用文件和文件夹）

# 安装 Intel RST for 傲腾

# 启用 组策略 (group policy) for Windows Home
if ($isWindowsHome) {
  $cmdCommandStr = 
@"
@echo off
pushd "%~dp0"
dir /b C:\Windows\servicing\Packages\Microsoft-Windows-GroupPolicy-ClientExtensions-Package~3*.mum >List.txt
dir /b C:\Windows\servicing\Packages\Microsoft-Windows-GroupPolicy-ClientTools-Package~3*.mum >>List.txt
for /f %%i in ('findstr /i . List.txt 2^>nul') do dism /online /norestart /add-package:"C:\Windows\servicing\Packages\%%i"
"@

  $batFilePath = "$tempDirPath/run.bat"
  $cmdCommandStr | Out-File 'utf8' -FilePath $batFilePath
  .$batFilePath
  Remove-Item $batFilePath
}






# 启用 administrator 账户
if ($isEnableAdministrator) {
  net user administrator /active:yes
}

# 设置键盘映射，可以使用 KeybMap（需要设为全局映射，当前用户映射可能无效） 或是直接操作注册表
{
  # this one echanges caps lock and esc (such value can be generated by KeybMap)
  $valueString = '0,0,0,0,0,0,0,0,3,0,0,0,3A,0,1,0,1,0,3A,0,0,0,0,0'
  $value = ($valueString -split ',') | ForEach-Object -Process { [System.Convert]::ToByte($_,16) }
  
  $keyboardLayoutKeyPath = 'HKLM:\SYSTEM\CurrentControlSet\Control\Keyboard Layout'
  $scancodeMapName =  'Scancode Map'
  $scancodeMapProperty = Get-ItemProperty -Path $keyboardLayoutKeyPath -Name $scancodeMapName

  # set scancode map property value
  if ($scancodeMapProperty) { # if scancode map property already exists 
    Set-ItemProperty -Path $keyboardLayoutKeyPath -Name $scancodeMapName -Value $value
  } else { # create scancode map property if it does not exist
    New-ItemProperty -Path $keyboardLayoutKeyPath -Name $scancodeMapName -Value $value -PropertyType binary
  }
}

# 设置 Hosts
{
  # Edit-Hosts.ps1
  $hostFilePath = "$env:windir/System32/drivers/etc/hosts"

  if ($blockUrls.Count -gt 1) {
    $blockUrlLines = $blockUrls | ForEach-Object { "127.0.0.1 $_" }
    # Note: '' adds a empty line between current content and the new content
    $blockContent = @('', '# Block urls') + $blockUrlLines
    # Note: Get-Content returns string of lines
    $newContent = (Get-Content $hostFilePath) + $blockContent
    Set-Content $hostFilePath $newContent
  }

  if ($isManualEditHostFile) {
    edit $hostFilePath
  }
}



# 安装和配置常用软件

# Edge
{
  # 移除 Edge 现有 Cache 目录，同时硬链接到 Ramdisk 下
  . "$scriptFileDirPath/EdgeBrowser.ps1"
  Set-EdgeBrowserCache -edgeSettingsPath "C:\Users\$userName\AppData\Local\Microsoft\Edge\User Data\Default" -newCacheRootPath "$ramDiskPath\Cache\Edge"
}

# Firefox
{
  # 拷贝配置文件夹，覆盖当前配置文件夹
  # 配置 gooreplacer
}

# Office
{
  # 安装 Office
  # Note: 直接点击安装的是32bit版本，点击office文件下的 Setup64.exe ；需启动 Windows Installer 服务

  # 安装 Visio
  # 如果更新 Office 时出现错误代码 30182-1 (2)，则将 HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Configuration\AllowCdnFallback : "True" （在 Configuration 下新建字符串值 True）
  # @see https://support.microsoft.com/zh-cn/office/%e6%9b%b4%e6%96%b0-office-%e6%97%b6%e5%87%ba%e7%8e%b0%e9%94%99%e8%af%af%e4%bb%a3%e7%a0%81-30182-1-2-6a8d49a6-db50-40d1-9a70-1f93b095c774?ns=ocsac2rclientupdate&version=16&syslcid=2052&uilcid=2052&appver=cle160&helpid=%222-1-30182%22&ui=zh-cn&rs=zh-cn&ad=cn

  # 设置 Office 选项，关闭 Office 更新/遥测/开始页
}



# 安装和配置开发环境和软件

# JDK
# Optional: JRE8 for JNLP，关闭更新和控制台，允许 http://192.168.2.126

# git
# 令git保存输入的账号密码
git config --global credential.helper store

# Miktex & TexWorks
# 导入 TexWorks 配置

# VS

{
  # 禁止参与 VS Experience Improvement Program
  # Help - Send Feedback

  # 删除右键菜单 “在visual studio中打开”
  Get-Item Registry::HKEY_CLASSES_ROOT\Directory\Background\shell\AnyCode | Remove-Item -Recurse
  Get-Item Registry::HKEY_CLASSES_ROOT\Directory\shell\AnyCode | Remove-Item -Recurse
}

# IDEA



# 完成所有安装后的设置

# 禁用 Windows 更新
{
  . "$scriptFileDirPath/WindowsUpdate.ps1"
  Disable-WindowsUpdateRelatedService
  Clear-WindowsUpdateLog
  Clear-WindowsUpdateDownloadDirectory -createFakeFile

  # 在组策略中禁用更新策略
  # gpedit.msc
  # 计算机配置 – 管理模块 – windows组件 – windows更新 –配置自动更新 – 已禁用
}

# 禁用不必要的计划任务，部分任务仅管理员权限不够，需要System权限
{
  # 禁用这些路径下的所有任务
  $pathsToDisable = 
    #'\Microsoft\Windows\UpdateOrchestrator\',
    '\Microsoft\Windows\Customer Experience Improvement Program\',
    '\Microsoft\Office\'

  # 禁用指定任务
  $pathAndNamesToDisable = 
    @('\Microsoft\Windows\WindowsUpdate\', 'Scheduled Start'),
    @('\Microsoft\VisualStudio\Updates\', 'BackgroundDownload')

  Get-ScheduledTask -TaskPath $pathsToDisable | Disable-ScheduledTask
  
  foreach ($pathAndName in $pathAndNamesToDisable) {
    Get-ScheduledTask -TaskPath $pathAndName[0] -TaskName $pathAndName[1] | Disable-ScheduledTask
  }
}

# 清理注册表右键新建菜单
{
  # 打开 Regedit，HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Discardable\PostSetup\ShellNew，删除 Classes 中的多余项
  # 搜索 HKEY_LOCAL_MACHINE\SOFTWARE\Classes 下的对应扩展名项，删除对应的 ShellNew 项
}

# 设置 sendto
{
  # explorer 打开 shell:sendto，删除无用项，添加指向 RAMDisk 的项
}